env:
  browser: true
extends: 'airbnb-base'
rules:
  no-console:
    - error
    - allow:
      - warn
      - error
  consistent-return: off
  func-names: off
  no-alert: off
  no-bitwise: off
  no-extend-native: off
  no-param-reassign: off
  no-plusplus: off
  no-var: off
  object-shorthand: off
  one-var: off
  prefer-arrow-callback: off
  prefer-destructuring: off
  prefer-template: off
  vars-on-top: off
globals:
  GM_getValue: false
  GM_setValue: false
  gmGet: true
  gmSet: true
